name: docker

on:
  workflow_dispatch:
    # If triggered from UI, by default, docker tags will be
    #  - ghcr.io/gabrie30/ghorg:dev-latest
    #  - ghcr.io/gabrie30/ghorg:dev-run-<GITHUB_RUN_NUMBER>
    inputs:
      docker_latest_tag:
        required: false
        type: string
        default: dev-latest
      docker_tag:
        required: false
        type: string
        default: dev-run-${{ GITHUB_RUN_NUMBER }}
  workflow_call:
    # If triggered from another WF, by default, docker tags will be
    #  - ghcr.io/gabrie30/ghorg:dev-latest
    #  - ghcr.io/gabrie30/ghorg:dev-<GITHUB_REF_NAME>
    inputs:
      docker_latest_tag:
        required: true
        type: string
        default: latest
      docker_tag:
        required: true
        type: string

jobs:
  docker:
    name: Build and deploy to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ inputs.docker_latest_tag }}
            ghcr.io/${{ github.repository }}:${{ inputs.docker_tag }}
