name: goreleaser

on:
  push:
    tags:
      - 'v*'
    branches:
      - 351/automated_docker_images
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # goreleaser:
  #   environment: actions
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     -
  #       name: Set up Go
  #       uses: actions/setup-go@v4
  #     -
  #       name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v4
  #       with:
  #         distribution: goreleaser
  #         version: latest
  #         args: release --clean
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GHORG_GITHUB_TOKEN }}

  docker:
    # needs: inputs
    name: Build and deploy to GitHub Container Registry
    # if: needs.inputs.outputs.version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     registry: docker.io
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # context: ./ghorg
          # file: Dockerfile
          platforms: linux/arm,linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/afonsoc12/${{ github.repository }}:latest
            ghcr.io/afonsoc12/${{ github.repository }}:dev-${GITHUB_SHA::7}
