name: goreleaser

on:
  push:
    tags:
      - 'v*'
    branches:
      - 351/automated_docker_images
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # goreleaser:
  #   environment: actions
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     -
  #       name: Set up Go
  #       uses: actions/setup-go@v4
  #     -
  #       name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v4
  #       with:
  #         distribution: goreleaser
  #         version: latest
  #         args: release --clean
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GHORG_GITHUB_TOKEN }}

  docker:
    steps:
      - name: Generate short commit GITHUB_SHA::7
        run: echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Run reusable docker workflow
        uses: ./.github/workflows/docker.yml@HEAD
        with:
          docker_latest_tag: dev-latest
          docker_tag: dev-${{ env.commit_sha }}

