name: goreleaser

on:
  push:
    tags:
      - 'v*'
    branches:
      - 351/automated_docker_images
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # goreleaser:
  #   environment: actions
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     -
  #       name: Set up Go
  #       uses: actions/setup-go@v4
  #     -
  #       name: Run GoReleaser
  #       uses: goreleaser/goreleaser-action@v4
  #       with:
  #         distribution: goreleaser
  #         version: latest
  #         args: release --clean
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GHORG_GITHUB_TOKEN }}

  docker-latest:
      uses: ./.github/workflows/docker.yml
      permissions:
        packages: write
      with:
        is_release: false

